name: Periodic health check

on:
  schedule:
    cron: '30 8 * * 6'

jobs:
  url_health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://green-butterfly-4308.fly.dev/health
      - name: Test Failure
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ failure() }}
        with:
          severity: error
          details: Health check failed
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
